<p>
    Hi <?php echo $user->getEmail(); ?>,
</p>

<p>
    There was recently a request to change the password on your account. If you requested this password
    change, please set a new password by following the link below:
</p>

<?php $url = $this->url('zfcuser/forgotpasswordreset', array('token' => $token)); ?>

<p>
    <a href="<?php echo $url; ?>"><?php echo $url; ?></a>
</p>

<p>
    Please note that this link is valid only for <?php echo $options->getForgotRequestValid(); ?> hours.
</p>

<p>
    If you don't want to change your password, just ignore this message.
</p>

<p>
    Thanks
</p>