language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer update --prefer-source; composer install --dev --prefer-source;

script:
  - ./vendor/bin/phpunit --bootstrap=tests/bootstrap.php --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs -n --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v