<?php
return array(
    'ZfcUser\Module'                                   => __DIR__ . '/Module.php',
    'ZfcUser\Service\User'                             => __DIR__ . '/src/ZfcUser/Service/User.php',
    'ZfcUser\Document\UserMappedSuperClass'            => __DIR__ . '/src/ZfcUser/Document/UserMappedSuperClass.php',
    'ZfcUser\Document\User'                            => __DIR__ . '/src/ZfcUser/Document/User.php',
    'ZfcUser\Model\UserInterface'                      => __DIR__ . '/src/ZfcUser/Model/UserInterface.php',
    'ZfcUser\Model\UserMeta'                           => __DIR__ . '/src/ZfcUser/Model/UserMeta.php',
    'ZfcUser\Model\UserMetaInterface'                  => __DIR__ . '/src/ZfcUser/Model/UserMetaInterface.php',
    'ZfcUser\Model\User'                               => __DIR__ . '/src/ZfcUser/Model/User.php',
    'ZfcUser\Event\ResolveTargetEntityListener'        => __DIR__ . '/src/ZfcUser/Event/ResolveTargetEntityListener.php',
    'ZfcUser\Util\Password'                            => __DIR__ . '/src/ZfcUser/Util/Password.php',
    'ZfcUser\Controller\Plugin\ZfcUserAuthentication'  => __DIR__ . '/src/ZfcUser/Controller/Plugin/ZfcUserAuthentication.php',
    'ZfcUser\Controller\UserController'                => __DIR__ . '/src/ZfcUser/Controller/UserController.php',
    'ZfcUser\Mapper\UserMetaZendDb'                    => __DIR__ . '/src/ZfcUser/Mapper/UserMetaZendDb.php',
    'ZfcUser\Mapper\UserZendDb'                        => __DIR__ . '/src/ZfcUser/Mapper/UserZendDb.php',
    'ZfcUser\Mapper\UserInterface'                     => __DIR__ . '/src/ZfcUser/Mapper/UserInterface.php',
    'ZfcUser\Mapper\UserMetaDoctrine'                  => __DIR__ . '/src/ZfcUser/Mapper/UserMetaDoctrine.php',
    'ZfcUser\Mapper\UserMetaInterface'                 => __DIR__ . '/src/ZfcUser/Mapper/UserMetaInterface.php',
    'ZfcUser\Mapper\UserDoctrine'                      => __DIR__ . '/src/ZfcUser/Mapper/UserDoctrine.php',
    'ZfcUser\Authentication\Adapter\ChainableAdapter'  => __DIR__ . '/src/ZfcUser/Authentication/Adapter/ChainableAdapter.php',
    'ZfcUser\Authentication\Adapter\AdapterChainEvent' => __DIR__ . '/src/ZfcUser/Authentication/Adapter/AdapterChainEvent.php',
    'ZfcUser\Authentication\Adapter\AbstractAdapter'   => __DIR__ . '/src/ZfcUser/Authentication/Adapter/AbstractAdapter.php',
    'ZfcUser\Authentication\Adapter\AdapterChain'      => __DIR__ . '/src/ZfcUser/Authentication/Adapter/AdapterChain.php',
    'ZfcUser\Authentication\Adapter\Db'                => __DIR__ . '/src/ZfcUser/Authentication/Adapter/Db.php',
    'ZfcUser\Authentication\Storage\Db'                => __DIR__ . '/src/ZfcUser/Authentication/Storage/Db.php',
    'ZfcUser\Entity\UserMappedSuperClass'              => __DIR__ . '/src/ZfcUser/Entity/UserMappedSuperClass.php',
    'ZfcUser\Entity\UserMetaMappedSuperClass'          => __DIR__ . '/src/ZfcUser/Entity/UserMetaMappedSuperClass.php',
    'ZfcUser\Entity\UserMeta'                          => __DIR__ . '/src/ZfcUser/Entity/UserMeta.php',
    'ZfcUser\Entity\User'                              => __DIR__ . '/src/ZfcUser/Entity/User.php',
    'ZfcUser\View\Helper\ZfcUserIdentity'              => __DIR__ . '/src/ZfcUser/View/Helper/ZfcUserIdentity.php',
    'ZfcUser\Form\Login'                               => __DIR__ . '/src/ZfcUser/Form/Login.php',
    'ZfcUser\Form\Register'                            => __DIR__ . '/src/ZfcUser/Form/Register.php',
    'ZfcUser\Form\Base'                                => __DIR__ . '/src/ZfcUser/Form/Base.php',
);