<?php
return array(
    'EdpUser\Module'                                 => __DIR__ . '/Module.php',
    'EdpUser\Service\User'                           => __DIR__ . '/src/EdpUser/Service/User.php',
    'EdpUser\Document\UserMappedSuperClass'          => __DIR__ . '/src/EdpUser/Document/UserMappedSuperClass.php',
    'EdpUser\Document\User'                          => __DIR__ . '/src/EdpUser/Document/User.php',
    'EdpUser\Model\UserInterface'                    => __DIR__ . '/src/EdpUser/Model/UserInterface.php',
    'EdpUser\Model\UserMeta'                         => __DIR__ . '/src/EdpUser/Model/UserMeta.php',
    'EdpUser\Model\UserMetaInterface'                => __DIR__ . '/src/EdpUser/Model/UserMetaInterface.php',
    'EdpUser\Model\User'                             => __DIR__ . '/src/EdpUser/Model/User.php',
    'EdpUser\Event\ResolveTargetEntityListener'      => __DIR__ . '/src/EdpUser/Event/ResolveTargetEntityListener.php',
    'EdpUser\Util\Password'                          => __DIR__ . '/src/EdpUser/Util/Password.php',
    'EdpUser\Controller\UserController'              => __DIR__ . '/src/EdpUser/Controller/UserController.php',
    'EdpUser\Mapper\UserMetaZendDb'                  => __DIR__ . '/src/EdpUser/Mapper/UserMetaZendDb.php',
    'EdpUser\Mapper\UserZendDb'                      => __DIR__ . '/src/EdpUser/Mapper/UserZendDb.php',
    'EdpUser\Mapper\UserInterface'                   => __DIR__ . '/src/EdpUser/Mapper/UserInterface.php',
    'EdpUser\Mapper\UserMetaDoctrine'                => __DIR__ . '/src/EdpUser/Mapper/UserMetaDoctrine.php',
    'EdpUser\Mapper\UserMetaInterface'               => __DIR__ . '/src/EdpUser/Mapper/UserMetaInterface.php',
    'EdpUser\Mapper\UserDoctrine'                    => __DIR__ . '/src/EdpUser/Mapper/UserDoctrine.php',
    'EdpUser\Authentication\AuthenticationService'   => __DIR__ . '/src/EdpUser/Authentication/AuthenticationService.php',
    'EdpUser\Authentication\AuthEvent'               => __DIR__ . '/src/EdpUser/Authentication/AuthEvent.php',
    'EdpUser\Authentication\Adapter'                 => __DIR__ . '/src/EdpUser/Authentication/Adapter.php',
    'EdpUser\Authentication\Adapter\AbstractAdapter' => __DIR__ . '/src/EdpUser/Authentication/Adapter/AbstractAdapter.php',
    'EdpUser\Authentication\Adapter\Db'              => __DIR__ . '/src/EdpUser/Authentication/Adapter/Db.php',
    'EdpUser\Entity\UserMappedSuperClass'            => __DIR__ . '/src/EdpUser/Entity/UserMappedSuperClass.php',
    'EdpUser\Entity\UserMetaMappedSuperClass'        => __DIR__ . '/src/EdpUser/Entity/UserMetaMappedSuperClass.php',
    'EdpUser\Entity\UserMeta'                        => __DIR__ . '/src/EdpUser/Entity/UserMeta.php',
    'EdpUser\Entity\User'                            => __DIR__ . '/src/EdpUser/Entity/User.php',
    'EdpUser\View\Helper\EdpUser'                    => __DIR__ . '/src/EdpUser/View/Helper/EdpUser.php',
    'EdpUser\View\Helper\EdpUserService'             => __DIR__ . '/src/EdpUser/View/Helper/EdpUserService.php',
    'EdpUser\Form\Login'                             => __DIR__ . '/src/EdpUser/Form/Login.php',
    'EdpUser\Form\Register'                          => __DIR__ . '/src/EdpUser/Form/Register.php',
    'EdpUser\Form\Base'                              => __DIR__ . '/src/EdpUser/Form/Base.php',
);