<h1>Sign In</h1>
<?php

$form = $this->loginForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

$this->form()->openTag($form);

$elements = $form->getElements();
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('identity')); ?></dt>
<dd><?php
echo $this->formInput($form->get('identity'));
echo $this->formElementErrors($form->get('identity'));
?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('credential'));
echo $this->formElementErrors($form->get('credential'));
?></dd>

<dd><?php
echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>

<?php //echo $loginForm->setAction($this->url('zfcuser/login'))->setView($this); ?>
Not registered? <a href="<?php echo $this->url('zfcuser/register') ?>">Sign up!</a>
