<h3>Change Password for <?php echo $this->zfcUserDisplayName() ?><h3>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dd><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('credential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('newCredential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
<dd><?php
echo $this->formInput($form->get('newCredentialVerify'));
?></dd>

<dd><?php
//echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>