<h3><?= sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()) ?></h3>
<?php if ($status === true) : ?>
    <div class="alert alert-success"><?= $this->translate('Email address changed successfully.') ?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-error"><?= $this->translate('Unable to update your email address. Please try again.') ?></div>
<?php endif; ?>

<?php
/** @var $form \Zend\Form\Form */
$form = $this->changeEmailForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changeemail'));
$form->setAttribute('method', 'post');
?>

<?= $this->form()->openTag($form) ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?= $this->redirect ?>" />
    <?php endif ?>
    <?= $this->formCollection($form) ?>
<?= $this->form()->closeTag() ?>
