<h3><?= sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()) ?></h3>
<?php if ($status === true) : ?>
    <div class="alert alert-success"><?= $this->translate('Password changed successfully.') ?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-error"><?= $this->translate('Unable to update your password. Please try again.') ?></div>
<?php endif; ?>

<?php
/** @var $form \Zend\Form\Form */
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
?>

<?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
<?= $this->form()->closeTag() ?>
