<h3>Forgot Password</h3>
<?php if ($status === true) : ?>
    <div class="alert alert-success">An email has been sent to reset your password.</div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-error">Unable to find an account associated with that email.</div>
<?php endif; ?>
<?php
/** @var $form \Zend\Form\Form */
$form = $this->forgotPasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/forgotpassword'));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dt><?php echo $this->formLabel($form->get('identity')); ?></dt>
<dd><?php
    echo $this->formInput($form->get('identity')) . $this->formElementErrors($form->get('identity'));
    ?>
</dd>

<dd><?php
//echo $this->formInput($form->get('csrf'));
    echo $this->formInput($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>
