<?php
/** @var \ZfcUser\View\Helper\IdentityHelper $identityHelper */
$identityHelper = $this->plugin('ZfcUser\View\Helper\IdentityHelper');
?>

<div style="float:left; padding-right:16px;">
    <?= $this->gravatar($identityHelper()->getEmail()) ?>
</div>
<h3><?= $this->translate('Hello'); ?>, <?= $identityHelper()->getEmail() ?>!</h3>
<a href="<?= $this->url('zfcuser/logout') ?>">[<?= $this->translate('Sign Out') ?>]</a>
