<h1>Sign In</h1>
<?php

$form = $this->loginForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dt><?php echo $this->formLabel($form->get('identity')); ?></dt>
<dd><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('credential'));
?></dd>

<?php if ($this->redirect): ?>
<input type="hidden" name="redirect" value="<?php echo $this->redirect; ?>" />
<?php endif; ?>

<dd><?php
//echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>

Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
