<h1><?= $this->translate('Sign In') ?></h1>

<?php
/** @var $form \Zend\Form\Form */
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?= $this->flashMessenger()->render(Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR) ?>

<?= $this->form()->openTag($form) ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?= $this->escapeHtml($this->redirect) ?>">
    <?php endif ?>
    <?= $this->formCollection($form) ?>
<?= $this->form()->closeTag() ?>

<?php if ($this->enableRegistration): ?>
    <?= $this->translate('Not registered?') ?> <a href="<?= $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?= $this->translate('Sign up!') ?></a>
<?php endif; ?>
