<h1>Register</h1>

<?php
if(!$this->enableRegistration)
{
    print "Registration is disabled";
    return;
}
?>

<?php

$form = $this->registerForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>

<dl class="zend_form">

<?php foreach ($form->getElements() as $element) { ?>
    <?php if ($element->getLabel() != null) { ?>
    <dt><?php echo $this->formLabel($element); ?></dt>
    <?php } ?>
    <?php if ($element instanceof Zend\Form\Element\Button) { ?>
    <dd><?php echo $this->formButton($element) ?></dd>    
    <?php } elseif ($element instanceof Zend\Form\Element\Captcha) { ?>
    <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element); ?></dd>    
    <?php } else { ?>
    <dd><?php echo $this->formInput($element) . $this->formElementErrors($element); ?></dd>
    <?php } ?>
<?php } ?>

</dl>

<?php if ($this->redirect): ?>
<input type="hidden" name="redirect" value="<?php echo $this->redirect; ?>" />
<?php endif; ?>

</form>

<?php //echo $registerForm->setAction($this->url('zfcuser/register'))->setView($this); ?>
