<h1><?= $this->translate('Register') ?></h1>

<?php if (!$this->enableRegistration): ?>
    <?= $this->translate('Registration is disabled') ?>
    <?php return; ?>
<?php endif; ?>

<?php
/** @var \Zend\Form\Form $form */
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?= $this->form()->openTag($form) ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?= $this->escapeHtml($this->redirect) ?>">
    <?php endif ?>
    <?= $this->formCollection($form) ?>
<?= $this->form()->closeTag() ?>
