-- Auto-generated by Doctrine; formatted with http://www.dpriver.com/pp/sqlformat.htm
CREATE TABLE USER
  (
     user_id       INT AUTO_INCREMENT NOT NULL,
     username      VARCHAR(255) DEFAULT NULL,
     email         VARCHAR(255) NOT NULL,
     display_name  VARCHAR(50) DEFAULT NULL,
     password      VARCHAR(128) NOT NULL,
     last_login    DATETIME DEFAULT NULL,
     last_ip       INT DEFAULT NULL,
     register_time DATETIME NOT NULL,
     register_ip   INT NOT NULL,
     active        TINYINT(1) NOT NULL,
     enabled       TINYINT(1) NOT NULL,
     UNIQUE INDEX uniq_8d93d649f85e0677 (username),
     UNIQUE INDEX uniq_8d93d649e7927c74 (email),
     PRIMARY KEY(user_id)
  )
ENGINE = INNODB 
